import { Server, utils } from "ssh2";

export interface MockSshServer {
  readonly port: number;
  readonly clientPrivateKey: string;
  close(): Promise<void>;
}

/**
 * A real, local-only SSH server (loopback, ephemeral port) backed by `ssh2.Server` — used so
 * integration tests exercise the real `ssh2.Client` connect/exec/close lifecycle in
 * `packages/execution-ssh/src/ssh/client.ts` instead of mocking `ssh2.Client` as every unit test
 * already does. Never a real remote host (Fase 14, DEC-072) — this process and the "remote" it
 * connects to are the same machine, same test run; fresh ed25519 keypairs generated per server
 * instance, never written to disk or committed anywhere.
 *
 * Accepts any publickey authentication attempt (there is only ever one client key in a given
 * test, generated by this same function) and always runs the exact command it receives via a
 * trivial handler that echoes it back on stdout — enough for a test to assert the whole real SSH
 * round trip (connect, authenticate, exec, read stdout, exit code, close) actually happened.
 */
export async function startMockSshServer(): Promise<MockSshServer> {
  const hostKeys = utils.generateKeyPairSync("ed25519");
  const clientKeys = utils.generateKeyPairSync("ed25519");

  const server = new Server({ hostKeys: [hostKeys.private] }, (client) => {
    client
      .on("error", () => {
        // A client process killed mid-connection (as integration tests do in `afterEach`, via
        // `spawnTestProcess.close()`'s `child.kill()`) resets the underlying TCP socket — this is
        // expected teardown noise for a test double, not a real server fault, and must never
        // surface as an uncaught exception in the test process.
      })
      .on("authentication", (ctx) => {
        if (ctx.method === "publickey") {
          ctx.accept();
        } else {
          ctx.reject(["publickey"]);
        }
      })
      .on("ready", () => {
        client.on("session", (accept) => {
          const session = accept();
          session.on("exec", (acceptExec, _reject, info) => {
            const channel = acceptExec();
            channel.stdout.write(`echo-from-mock-ssh-server:${info.command}\n`);
            channel.exit(0);
            channel.end();
          });
        });
      });
  });
  // Same reasoning as the per-client "error" handler above, but for a reset that arrives before
  // any client session was ever established.
  server.on("error", () => {});

  await new Promise<void>((resolve) => {
    server.listen(0, "127.0.0.1", resolve);
  });
  const address = server.address();
  if (address === null || typeof address === "string") {
    throw new Error("Mock SSH server failed to bind to a TCP port");
  }

  return {
    port: address.port,
    clientPrivateKey: clientKeys.private,
    close: () =>
      new Promise((resolve) => {
        server.close(() => resolve());
      }),
  };
}
